# Generated by Django 2.2 on 2019-03-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfibo',
            name='fibo',
            field=models.BigIntegerField(null=True),
        ),
    ]
