# Generated by Django 2.2 on 2019-03-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0002_auto_20190307_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfibo',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
