# Generated by Django 2.2 on 2019-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fibo', '0003_auto_20190307_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfibo',
            name='fibo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
