# Generated by Django 3.0 on 2019-12-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('app_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('multiplier', models.FloatField()),
                ('spends', models.PositiveIntegerField()),
                ('available_cashback', models.PositiveIntegerField()),
            ],
        ),
    ]
